### PR TITLE
Make `flutter run` work

### PR DESCRIPTION
**Pull request by elimisteve**

### CODE REVIEW

**Comment by siliconwitch** [comment]
`flutter run --release` seems to work

**Comment by elimisteve** [comment]
Did you test on Android or just iOS?

On Android I had to make the changes in this PR.

For the `--release` flag to work I also needed to make a signing key; see my other PR for that.

**Comment by siliconwitch** [comment]
Yeah, this is on Android 🤔 is there any difference (other than signing) for you between `flutter run` and `flutter run --release`?

**Comment by elimisteve** [comment]
The differences: https://chatgpt.com/share/e8d34fa0-a02d-4213-99ab-fddbe817bc2f

I may be running a newer version of Kotlin than you guys and thus needed newer deps as well? Not sure, but I had to specify the Kotlin version for my build to work.

**Pull request closed without merging**
