### PR TITLE
Custom API endpoint done

### PR DESCRIPTION
**Pull request by uma-shankar-TE**
User can use there custom server by adding their

- `API  endpoint`
- `API Header Key`
- `API Header Value`

a POST request will be sent as `multipart/form-data` to the endpoint
with following fields

- `audio` - audio file
- `image` - image file
- `location` -  location as string ( eg. street, city, country)
- `time` -  a string  eg.  `2024-09-19 22:59:19.150`
- `messages` a stringified json of message list 

where each message  will be 
```
{
 content : "hello"
 role : "assistant" or "user" 
}
```

expected response should contain
```
{
  user_prompt :  "hello",
  message : "How can i help you?"
  image : <base64> (optional)
  audio: <base64> (optional)
  debug :  {
    "topic_changed": true <or false>
  }
}
```

### CODE REVIEW

**Comment by eons44** [comment]
I tested this & it all looks great!
(Note 20 Ultra, US).

The custom endpoint is not compatible out of the box with https://github.com/brilliantlabsAR/noa-assistant running on http (at least not mine). I deployed noa-assistant to Andronix, so proot on the same device as the noa-flutter, then used `http://localhost:9666/mm` as the custom server address. The requests make it to the Assistant server, but it always replies with something like "invalid http request" (can't get the actual error cause the Frame refuses to pair without the reset button on Mister Power held down right now).

I'll keep working on debugging that and will reply back if I find anything actionable. For now, my only advice is to couple this PR with docs on how users can set up their own servers.

Thanks for your work on this one @uma-shankar-TE!

**Comment by uma-shankar-TE** [comment]
you are right @eons44 noa-assistant is just  assistant part of the system, noa-assistant can be used as an assistant service , behind a proxy server to control security and tokens.
Will try to give a PR in noa-assistant to work with app out of the box locally

**Comment by eons44** [comment]
Thanks @uma-shankar-TE !
That would be much appreciated.

Also, looking through this again, was it intentional to remove the text to speech option when using a custom server? It seems logical to offload the temperature and all that to the backend server, but I thought the TTS would (or not) be done by the app regardless of the server response. If that's just my ignorance, it might be worth noting the intended behavior as a tooltip or just in some docs at some point.

Thanks again!

**Comment by uma-shankar-TE** [comment]
> Thanks @uma-shankar-TE ! That would be much appreciated.
> 
> Also, looking through this again, was it intentional to remove the text to speech option when using a custom server? It seems logical to offload the temperature and all that to the backend server, but I thought the TTS would (or not) be done by the app regardless of the server response. If that's just my ignorance, it might be worth noting the intended behavior as a tooltip or just in some docs at some point.
> 
> Thanks again!

@eons44 in next iteration dynamic fields will solve the issue, it will allow as many fields as user want to control via app

**Comment by curiosiate** [comment]
It would be nice if the API endpoint could provide custom Lua responses to requests, if wanted (and maybe that is what is upcoming with the dynamic fields?)

**Comment by louwers** [comment]
What is the format of the image required?

**Comment by iamthegone** [comment]
Could we get just a little information about the custom server? I put a webhook address in there to see if I could capture what’s coming off it and get nothing. Documentation?

**Comment by curiosiate** [comment]
> Could we get just a little information about the custom server? I put a webhook address in there to see if I could capture what’s coming off it and get nothing. Documentation?

Try this out, put together a basic test the other day to route to LMStudio. 
Sort of has chat context, and somewhat of an example of how to inject custom data in/react to triggers but also not the optimal route to do that long term vs for basic usage (such as for shoddy chat context without doing more things)


[BasicNoaServer](https://github.com/curiosiate/BasicNoaServer)

**Comment by iamthegone** [comment]
@curiosiate thank you! I just noticed that noa-assistant on the brilliantlabsAR repo is actually the server. I’m going to take a look at your example for reference also. I have a knowledge graph and vector database setup and methods for context pulling already as well so it’ll be cool to see what you did. Thanks!

**Comment by uma-shankar-TE** [comment]
> What is the required encoding of the image / audio data?
@iamthegone 
 Response audio should be base64 encoded, and input audio and images will be as form fields (i.e binaries of jpeg and wav)

**Comment by CitizenOneX** [comment]
Updated expected response schema to contain `topic_changed` within `debug`, which is currently required in the `noa-flutter` app.
```
{
  user_prompt :  "hello",
  message : "How can i help you?"
  image : <base64> (optional)
  audio: <base64> (optional)
  debug :  {
    "topic_changed": true <or false>
  }
}
```

**Pull request merged**
